// GENERATED by scripts/gen-zones.mjs from the origins/zones/zone<N>/ folders: do not edit (npm run zones).
import zone1 from './zone1/zone.ts';
import spawns1 from './zone1/spawns.ts';
import kit1 from './zone1/kit.ts';
import looks1 from './zone1/look.ts';
import zone2 from './zone2/zone.ts';
import spawns2 from './zone2/spawns.ts';
import kit2 from './zone2/kit.ts';
import looks2 from './zone2/look.ts';
import mobLooks2 from './zone2/mob-looks.ts';

export const REGISTRY = {
  '1': { ...zone1, spawns: spawns1, kit: kit1, looks: looks1 },
  '2': { ...zone2, spawns: spawns2, kit: kit2, looks: looks2, mobLooks: mobLooks2 },
};
