// Origins patrons: the one reader of the patron list. The source of truth is docs/specs/origins/legends-500.csv (Expansion's legends PR,
// `expansion/legends-500`); `patronsFromCsv` keeps its rows with kind=patron, and generate.ts writes them to patrons.data.ts so the game and
// the preview import plain data with no CSV parse at runtime. patrons.test.ts regenerates from the CSV whenever the CSV is in the tree and
// fails on any drift, so the two can never disagree once the list is merged. Pure: no file system here.

export type PatronRow = {
  id: string;            // the CSV id, e.g. 'zeus'; the content id is `patron:${id}`
  name: string;
  group: string;         // pantheon or source family (greek, norse, gothic-lit, ...)
  source: string;        // the citation, as written in the list
  era: string;
  alignment: string;     // neutral | dark | light (flavour only: no rule reads it)
  clanTheme: string;     // the clan's line for the picker
  template: string;      // a perk-template id (patrons.ts PERK_TEMPLATES)
  pronoun: string;
};

// RFC 4180 lines: commas, double-quoted fields with "" escapes, quoted newlines. Throws on an unterminated quote (a broken file is a build
// error, never a partial list).
export function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [], field = '', quoted = false, i = 0;
  const body = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;   // a byte-order mark is not part of the first column name
  while (i < body.length) {
    const c = body[i]!;
    if (quoted) {
      if (c === '"' && body[i + 1] === '"') { field += '"'; i += 2; continue; }
      if (c === '"') { quoted = false; i++; continue; }
      field += c; i++; continue;
    }
    if (c === '"' && field === '') { quoted = true; i++; continue; }
    if (c === ',') { row.push(field); field = ''; i++; continue; }
    if (c === '\r' && body[i + 1] === '\n') i++;
    if (c === '\n' || c === '\r') { row.push(field); rows.push(row); row = []; field = ''; i++; continue; }
    field += c; i++;
  }
  if (quoted) throw new Error('csv: unterminated quoted field');
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows.filter((r) => !(r.length === 1 && r[0] === ''));
}

const COLUMNS = ['id', 'name', 'kind', 'group', 'source', 'era_or_date', 'alignment', 'clan_theme', 'perk_template', 'pronouns'] as const;

export function patronsFromCsv(text: string): PatronRow[] {
  const [head, ...rows] = parseCsv(text);
  if (!head) throw new Error('csv: empty');
  const at = Object.fromEntries(COLUMNS.map((c) => {
    const i = head.indexOf(c);
    if (i < 0) throw new Error(`csv: missing column ${c}`);
    return [c, i];
  })) as Record<(typeof COLUMNS)[number], number>;
  return rows.filter((r) => r[at.kind] === 'patron').map((r) => ({
    id: r[at.id]!, name: r[at.name]!, group: r[at.group]!, source: r[at.source]!, era: r[at.era_or_date]!, alignment: r[at.alignment]!,
    clanTheme: r[at.clan_theme]!, template: r[at.perk_template]!, pronoun: r[at.pronouns]!,
  }));
}

// The generated module's text: one row a line, so a list change reads as a line diff in review.
export function renderData(rows: readonly PatronRow[]): string {
  return [
    '// GENERATED by origins/patrons/generate.ts from docs/specs/origins/legends-500.csv (kind=patron rows). Do not edit by hand:',
    '// edit the CSV and run `node origins/patrons/generate.ts`. patrons.test.ts fails on drift whenever the CSV is in the tree.',
    "import type { PatronRow } from './csv.ts';",
    '',
    'export const PATRON_ROWS: readonly PatronRow[] = [',
    ...rows.map((r) => `  ${JSON.stringify(r)},`),
    '];',
    '',
  ].join('\n');
}
