// Generated by scripts/build-arena-audio.mjs. Regions are [offset, duration] seconds.
export const ARENA_MANIFEST = {"bed":[[0.02,8],[8.08,8],[16.14,8]],"reaction":[[24.2,1.05],[25.31,1.05],[26.42,1.05],[27.53,0.5]],"jeer":[[28.09,1.3],[29.45,1.3]],"chant":[[30.81,2.8],[33.67,2.8]],"grunt":[[36.53,0.24],[36.83,0.24],[37.13,0.24]],"bell":[[37.43,2.6]]} as const;
export type ArenaCue = keyof typeof ARENA_MANIFEST;
