// Generated by scripts/build-arena-audio.mjs. Regions are [offset, duration] seconds.
export const ARENA_MANIFEST = {"bed":[[0.02,6],[6.08,6],[12.14,6]],"reaction":[[18.2,1.05],[19.31,1.05],[20.42,1.05],[21.53,0.5]],"jeer":[[22.09,1.3],[23.45,1.3]],"chant":[[24.81,2.8],[27.67,2.8]],"grunt":[[30.53,0.24],[30.83,0.24],[31.13,0.24]],"bell":[[31.43,2.5]],"jeer_wall":[[33.99,3],[37.05,3],[40.11,3]]} as const;
export type ArenaCue = keyof typeof ARENA_MANIFEST;
