import { chromium } from 'playwright';
import { createServer } from 'vite';
import fs from 'node:fs/promises';
const out = process.argv[2];
const server = await createServer({ server: { host: '127.0.0.1', port: 0 }, logLevel: 'silent' }); await server.listen();
const browser = await chromium.launch({ headless: true, executablePath: chromium.executablePath() });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await page.goto(`${server.resolvedUrls.local[0]}character-preview.html`);
await page.waitForFunction(() => window.__preview?.loaded || window.__preview?.error, null, { timeout: 180000 });
const list = [['skin match', 'Idle', 0, 'Head', .85, .35, .05, [0, -.12, 0]], ['arm', 'Idle', 0, 'Head', .6, 1.2, -.1, [.25, -.25, 0]], ['legs', 'Idle', 0, 'Head', 1.0, .3, -.2, [0, -1.0, 0]], ['back', 'Idle', 0, 'Head', .85, 3.0, .05, [0, -.12, 0]]];
const data = await page.evaluate(l => __preview.details(l), list);
await fs.writeFile(out, Buffer.from(data.split(',')[1], 'base64'));
await browser.close(); await server.close();
