// Bake licensed/authored blade trajectories as pure numeric simulation data; run after building a rig or changing a weapon.
// One table per weapon and per (clip, timing) in that weapon's PATHS (src/moves.ts WEAPONS): the simulation sweeps these; renderer bones
// never own hits. Which rig, node and contact segment each weapon bakes from is scripts/blade-manifest.json (the weapons lane adds entries).
// A table belongs to the rig it was baked on (`rig`: the model identity that carries the scale; 'hero' = the man/player skeleton): the
// same knife sweeps 0.82 m elsewhere in the Goblin's hand than in the player's (measured 2026-09-21). `bladePathsByRig[rig][weapon]`
// holds every bake and is the only export; src/blade.ts looks a sweep up by (rig, weapon) and never falls through to another rig. An
// entry with `attach` bakes the player's equip file the way the runtime wears it: the rig's skeleton, the file's WeaponDrawn under
// hand_r at its own transform, the file's clips when it has any.
import fs from 'node:fs/promises';
import { AnimationMixer, Vector3 } from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { swingProgress } from '../src/blade.ts';
import { WEAPONS, total } from '../src/moves.ts';
globalThis.ProgressEvent=class {constructor(_,fields){Object.assign(this,fields)}};
const manifest=JSON.parse(await fs.readFile('scripts/blade-manifest.json','utf8'));
const byRig={};
const load=async file=>{ // geometry-free load: nodes, transforms and clips are all a bake needs
 const bytes=await fs.readFile(file), size=bytes.readUInt32LE(12), json=JSON.parse(bytes.subarray(20,20+size));
 json.images=[];json.textures=[];json.materials=(json.materials||[]).map(m=>({name:m.name}));
 json.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+size).toString('base64');
 return new GLTFLoader().parseAsync(JSON.stringify(json),'');
};
for(const entry of manifest.weapons) {
 const weapon=WEAPONS[entry.weapon]; if(!weapon) throw new Error(`blade-manifest: unknown weapon ${entry.weapon}`);
 if(!entry.rig) throw new Error(`blade-manifest: ${entry.weapon} needs a rig (the model the table is baked on; 'hero' = the player skeleton)`);
 const asset=await load(entry.glb);
 if(entry.attach) { // the equip file worn by this rig: its WeaponDrawn replaces the rig's sword in hand_r, its clips join the rig's
  const part=await load(entry.attach), node=part.scene.getObjectByName('WeaponDrawn'), hand=asset.scene.getObjectByName('hand_r');
  if(!node||!hand) throw new Error(`blade-manifest: ${entry.attach} needs WeaponDrawn and ${entry.glb} needs hand_r`);
  for(const old of ['WeaponDrawn','SwordDrawn','SwordSheathed']) asset.scene.getObjectByName(old)?.removeFromParent();
  hand.add(node); for(const clip of part.animations) { const i=asset.animations.findIndex(c=>c.name===clip.name); if(i<0) asset.animations.push(clip); else asset.animations[i]=clip; }   // the file's clips play over the rig's same-named ones (a re-keyed Heavy)
 }
 const mixer=new AnimationMixer(asset.scene), blade=asset.scene.getObjectByName(entry.node);
 if(entry.scale) asset.scene.scale.multiplyScalar(entry.scale);
 if(!blade) throw new Error(`blade-manifest: ${entry.glb} has no node ${entry.node}`);
 // The striking segment: the node's extras.contact wins over the manifest (a trident's tines, not its shaft).
 const contact=blade.userData?.contact ? [blade.userData.contact.from, blade.userData.contact.to] : entry.contact;
 if(!Array.isArray(contact)||contact.length!==2||!(contact[1]>contact[0])) throw new Error(`blade-manifest: bad contact segment for ${entry.weapon}`);
 const paths={};
 for(const [kind,spec] of Object.entries(weapon.paths)) {
  const length=total(spec),clip=asset.animations.find(c=>c.name===spec.clip); if(!clip) throw new Error(`${entry.glb} has no clip ${spec.clip} for ${entry.weapon}/${kind}`);
  const action=mixer.clipAction(clip).play(), override=blade.userData.contactByClip?.[spec.clip], strike=override?[override.from,override.to]:contact;
  paths[kind]=Array.from({length:length+1},(_,age)=>{
   mixer.setTime(Math.min(.999999,swingProgress(age/length,spec.windup/length,spec.source))*clip.duration);asset.scene.updateMatrixWorld(true);
   return strike.flatMap(y=>blade.localToWorld(new Vector3(0,y,0)).toArray().map(v=>+v.toFixed(5)));
  });action.stop();mixer.uncacheClip(clip);
 }
 (byRig[entry.rig]??={})[entry.weapon]=paths;
 console.log(`${entry.weapon}@${entry.rig}: ${Object.keys(paths).length} paths from ${entry.glb}${entry.attach?' + '+entry.attach:''}#${entry.node} (contact ${contact[0]}–${contact[1]} m), `+Object.values(paths).reduce((n,p)=>n+p.length,0)+' fixed-tick poses');
}
await fs.writeFile('src/blade-paths.ts','// Generated by scripts/bake-blades.mjs from scripts/blade-manifest.json. Do not hand-edit.\n// Every bake by the rig it was baked on: [rig][weapon][kind]. A table never serves another rig (src/blade.ts).\nexport const bladePathsByRig: Record<string, Record<string, Record<string, number[][]>>> = '+JSON.stringify(byRig)+';\n');
console.log(`Baked ${Object.values(byRig).reduce((n,w)=>n+Object.keys(w).length,0)} table(s) by rig: ${Object.entries(byRig).map(([r,w])=>`${r}[${Object.keys(w).join(',')}]`).join(' ')}`);
