// Bake licensed/authored blade trajectories as pure numeric simulation data; run after building the rig.
import fs from 'node:fs/promises';
import { AnimationMixer, Vector3 } from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { swingProgress } from '../src/blade.ts';
import { ATTACKS } from '../src/combat.ts';
const bytes=await fs.readFile('src/assets/warrior.glb'), size=bytes.readUInt32LE(12), json=JSON.parse(bytes.subarray(20,20+size));
json.images=[];json.textures=[];json.materials=json.materials.map(m=>({name:m.name}));
json.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+size).toString('base64');
globalThis.ProgressEvent=class {constructor(_,fields){Object.assign(this,fields)}};
const asset=await new GLTFLoader().parseAsync(JSON.stringify(json),''), mixer=new AnimationMixer(asset.scene), blade=asset.scene.getObjectByName('SwordDrawn');
const paths={};
for(const [kind,name,source] of [['light','Attack',18/66],['return','Return',1-18/66],['heavy','Heavy',.48],['riposte','Riposte',.34]]) {
 const spec=ATTACKS[kind],clip=asset.animations.find(c=>c.name===name),action=mixer.clipAction(clip).play();
 paths[kind]=Array.from({length:spec.recovery+1},(_,age)=>{
  mixer.setTime(Math.min(.999999,swingProgress(age/spec.recovery,spec.contact/spec.recovery,source))*clip.duration);asset.scene.updateMatrixWorld(true);
  return [.18,.86].flatMap(y=>blade.localToWorld(new Vector3(0,y,0)).toArray().map(v=>+v.toFixed(5)));
 });action.stop();
}
await fs.writeFile('src/blade-paths.ts','// Generated by scripts/bake-blades.mjs from warrior.glb. Do not hand-edit.\nexport const bladePaths: Record<string, number[][]> = '+JSON.stringify(paths)+';\n');
console.log('Baked four blade paths, '+Object.values(paths).reduce((n,p)=>n+p.length,0)+' fixed-tick poses');
