// Bake licensed/authored blade trajectories as pure numeric simulation data; run after building a rig or changing a weapon.
// One table per weapon and per (clip, timing) in that weapon's PATHS (src/moves.ts WEAPONS): the simulation sweeps these; renderer bones
// never own hits. Which rig, node and contact segment each weapon bakes from is scripts/blade-manifest.json (the weapons lane adds entries).
import fs from 'node:fs/promises';
import { AnimationMixer, Vector3 } from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { swingProgress } from '../src/blade.ts';
import { WEAPONS, total } from '../src/moves.ts';
globalThis.ProgressEvent=class {constructor(_,fields){Object.assign(this,fields)}};
const manifest=JSON.parse(await fs.readFile('scripts/blade-manifest.json','utf8'));
const tables={};
for(const entry of manifest.weapons) {
 const weapon=WEAPONS[entry.weapon]; if(!weapon) throw new Error(`blade-manifest: unknown weapon ${entry.weapon}`);
 const bytes=await fs.readFile(entry.glb), size=bytes.readUInt32LE(12), json=JSON.parse(bytes.subarray(20,20+size));
 json.images=[];json.textures=[];json.materials=json.materials.map(m=>({name:m.name}));
 json.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+size).toString('base64');
 const asset=await new GLTFLoader().parseAsync(JSON.stringify(json),''), mixer=new AnimationMixer(asset.scene), blade=asset.scene.getObjectByName(entry.node);
 if(!blade) throw new Error(`blade-manifest: ${entry.glb} has no node ${entry.node}`);
 // The striking segment: the node's extras.contact wins over the manifest (a trident's tines, not its shaft).
 const contact=blade.userData?.contact ? [blade.userData.contact.from, blade.userData.contact.to] : entry.contact;
 if(!Array.isArray(contact)||contact.length!==2||!(contact[1]>contact[0])) throw new Error(`blade-manifest: bad contact segment for ${entry.weapon}`);
 const paths={};
 for(const [kind,spec] of Object.entries(weapon.paths)) {
  const length=total(spec),clip=asset.animations.find(c=>c.name===spec.clip); if(!clip) throw new Error(`${entry.glb} has no clip ${spec.clip} for ${entry.weapon}/${kind}`);
  const action=mixer.clipAction(clip).play();
  paths[kind]=Array.from({length:length+1},(_,age)=>{
   mixer.setTime(Math.min(.999999,swingProgress(age/length,spec.windup/length,spec.source))*clip.duration);asset.scene.updateMatrixWorld(true);
   return contact.flatMap(y=>blade.localToWorld(new Vector3(0,y,0)).toArray().map(v=>+v.toFixed(5)));
  });action.stop();mixer.uncacheClip(clip);
 }
 tables[entry.weapon]=paths;
 console.log(`${entry.weapon}: ${Object.keys(paths).length} paths from ${entry.glb}#${entry.node} (contact ${contact[0]}–${contact[1]} m), `+Object.values(paths).reduce((n,p)=>n+p.length,0)+' fixed-tick poses');
}
// A placeholder weapon (data borrowed from another) bakes nothing of its own: it points at the table it borrows.
for(const [id,w] of Object.entries(WEAPONS)) if(w.placeholder && !tables[id]) { const source=Object.entries(WEAPONS).find(([k,o])=>!o.placeholder && o.moves===w.moves)?.[0]; if(source) tables[id]=tables[source]; }
await fs.writeFile('src/blade-paths.ts','// Generated by scripts/bake-blades.mjs from scripts/blade-manifest.json. Do not hand-edit.\nexport const bladePaths: Record<string, Record<string, number[][]>> = '+JSON.stringify(tables)+';\n');
console.log(`Baked ${Object.keys(tables).length} weapon table(s): ${Object.keys(tables).join(', ')}`);
