// Scripted conversion of the roster into catalogue rows (src/fight/catalogue.ts): one row per ROSTER character, the ten Pit ranks' legends inside the row. Pure data out, no rig code:
// every value is READ from the existing sources (src/roster.ts, src/legends.ts, src/loot.ts, the GLBs), none is typed here except the small override tables below, which are the facts
// no source holds yet (blood colour/amount, a beast's finisher picks, the world assets that exist). Writes src/fight/catalogue-rows.ts; the file is the source of truth after this run.
//   node scripts/catalogue-convert.mjs            (Node 24 strips the .ts imports)
import fs from 'node:fs';
import { ROSTER } from '../src/roster.ts';
import { LEGENDS } from '../src/legends.ts';
import { LOOT } from '../src/loot.ts';
import { ROTATION } from '../src/finishers.ts';

const glb = (path) => {
  const b = fs.readFileSync(path), g = JSON.parse(b.subarray(20, 20 + b.readUInt32LE(12)).toString('utf8'));
  const tris = g.meshes.flatMap((m) => m.primitives).reduce((n, p) => n + (p.indices === undefined ? 0 : g.accessors[p.indices].count / 3), 0);
  return { tris: Math.round(tris), joints: new Set((g.skins ?? []).flatMap((s) => s.joints.map((i) => g.nodes[i].name))), clips: (g.animations ?? []).map((a) => a.name) };
};
const ENGINE = (body) => ['src/assets', 'public/beasts'].map((d) => `${d}/${body}.glb`).find((p) => fs.existsSync(p));
// The world assets that exist (public/world, generated by scripts/character/world_body.py); the boar's world body is its engine file (already light).
const WORLD = { goblin: 'public/world/goblin.glb', knight: 'public/world/knight.glb', pitborn: 'public/world/pitborn.glb', witch: 'public/world/witch.glb', wolf: 'public/world/wolf.glb', bear: 'public/world/bear.glb', boar: 'public/beasts/boar.glb' };
const WORLD_MAX = 8200;
// Blood (Characters 2026-10-09, a starting point for Dom's eye at 375 wide; the Pit's own BLOOD is #690f0d -> #200504): beasts darker, the goblin small. The Skeleton is bloodless (roster blood: false).
const BEAST_BLOOD = { start: '#5a0b0a', end: '#1c0403' };
const BLOOD = { wolf: { ...BEAST_BLOOD, amount: 0.7 }, boar: { ...BEAST_BLOOD, amount: 1 }, bear: { ...BEAST_BLOOD, amount: 1.4 }, goblin: { start: '#5a1410', end: '#1c0604', amount: 0.6 } };
const MAN_BLOOD = { start: '#690f0d', end: '#200504', amount: 1 };
const BEASTS = new Set(['wolf', 'boar', 'bear']);
const ALL = [...ROTATION, 'quietOne'];   // a roster row with no `finishers` list allows every finisher (roster.ts supportsFinishers); the rotation ends in plainDeath as the safe fallback
const CREATURE_CITATION = { goblin: { work: 'Historia Ecclesiastica (the demon St Taurinus drove from the temple of Diana at Evreux, whom the people call Gobelinus)', author: 'Orderic Vitalis', year: 1141, locator: 'Bk. V (Le Prevost, vol. 3, p. 331; ch. 7 in Chibnall)' },
  wolf: { work: 'Kinder- und Hausmärchen, 7th ed. (Rotkäppchen: the wolf on the forest road)', author: 'Jacob and Wilhelm Grimm', year: 1857, locator: 'KHM 26, Rotkäppchen' },
  boar: { work: 'Metamorphoses (the boar Diana loosed on Calydon, and the hunt that took it)', author: 'Ovid', year: 8, locator: 'Bk. VIII, ll. 260-424' },
  bear: { work: 'Kinder- und Hausmärchen, 7th ed. (Schneeweißchen und Rosenrot: the bear at the cottage door in the snow)', author: 'Jacob and Wilhelm Grimm', year: 1857, locator: 'KHM 161, Schneeweißchen und Rosenrot' } };

// The bones a finisher may cut, found by NAME in the engine asset's own skin joints (the hero family: neck_01/Head/upperarm_*/thigh_*; the beast family: neck/head/front_up_*/hind_up_*); null if the rig names none.
function cutOf(joints) {
  const has = (...n) => n.filter((x) => joints.has(x));
  const head = has('Head', 'head', 'jaw'), neck = has('neck_01', 'neck');
  const limbs = Object.fromEntries(Object.entries({ armL: ['upperarm_l', 'front_up_L'], armR: ['upperarm_r', 'front_up_R'], legL: ['thigh_l', 'hind_up_L'], legR: ['thigh_r', 'hind_up_R'] }).map(([k, c]) => [k, has(...c)]));
  return head.length && neck.length && Object.values(limbs).every((l) => l.length) ? { head, neck, limbs } : null;
}
const beastLimbs = (cut) => cut && ({ ...cut, limbs: { foreL: cut.limbs.armL, foreR: cut.limbs.armR, hindL: cut.limbs.legL, hindR: cut.limbs.legR } });

const rows = Object.entries(ROSTER).map(([id, r]) => {
  const engineAsset = ENGINE(r.body), e = glb(engineAsset), wAsset = WORLD[id] ?? null, w = wAsset && (wAsset === engineAsset ? e : glb(wAsset));
  const cut = BEASTS.has(id) ? beastLimbs(cutOf(e.joints)) : cutOf(e.joints);
  const shape = BEASTS.has(id) ? 'quadruped' : 'biped';
  const finishers = BEASTS.has(id) ? ['decapitation', 'plainDeath'] : r.finishers ? (r.finishers.includes('plainDeath') ? r.finishers : [...r.finishers, 'plainDeath']) : ALL.filter((f) => f !== 'quietOne').concat(['quietOne']).filter((f) => f !== 'plainDeath').concat(['plainDeath']);
  return {
    id, name: r.name, rig: r.rig, shape,
    engine: { asset: engineAsset, tris: e.tris },
    world: w ? { asset: wAsset, tris: w.tris, generator: wAsset === engineAsset ? null : 'scripts/character/world_body.py', maxTris: WORLD_MAX } : null,
    armour: (LOOT[id] ?? []).filter((p) => !/\.(Knife|Cleaver|Trident|Estoc|Scythe|Warhammer|Maul|Gladius|Shield|Longsword|Reaper)$/.test(p)),
    stats: { archetype: r.archetype, levels: [1, 50] },
    animations: { clips: e.clips },
    finisher: { cut, finishers },
    blood: r.blood === false ? null : (BLOOD[id] ?? MAN_BLOOD),
    loot: { table: id === 'goblin' ? 'loottable:pit-goblin' : null },
    legend: LEGENDS[id] ? null : (CREATURE_CITATION[id] ?? { pending: 'no citation yet (held roster character)' }),
    ranks: LEGENDS[id] ? LEGENDS[id].map((l) => ({ name: l.name, source: l.source, backstory: l.backstory })) : [],
  };
});
const ts = (v, pad = '') => {   // TS literal: bare identifier keys, JSON strings (any apostrophe survives), numbers as they are
  const next = pad + '  ';
  if (Array.isArray(v)) return v.every((x) => typeof x !== 'object' || x === null) ? `[${v.map((x) => ts(x)).join(', ')}]` : `[\n${v.map((x) => next + ts(x, next)).join(',\n')},\n${pad}]`;
  if (v && typeof v === 'object') return `{ ${Object.entries(v).map(([k, x]) => `${/^[A-Za-z_]\w*$/.test(k) ? k : JSON.stringify(k)}: ${ts(x, next)}`).join(', ')} }`;
  return JSON.stringify(v);
};
const out = `// The character catalogue's rows (src/fight/catalogue.ts): one per roster character; the ten Pit ranks' legends live inside the row. GENERATED once by scripts/catalogue-convert.mjs from
// src/roster.ts, src/legends.ts, src/loot.ts and the GLBs (measured tri counts, clips, joints); this file is the source of truth from here on. A new character is one row. World assets are
// generated from the engine asset by scripts/character/world_body.py; a row with world null has none yet, so no zone may draw it. The goblin is row #1 of the camp (Lead 2026-10-09).
import type { CatalogueRow } from './catalogue.ts';

export const CATALOGUE: readonly CatalogueRow[] = ${ts(rows)};
export const catalogueRow = (id: string): CatalogueRow | null => CATALOGUE.find((r) => r.id === id) ?? null;
`;
fs.writeFileSync('src/fight/catalogue-rows.ts', out);
console.log(rows.length, 'rows;', rows.reduce((n, r) => n + r.ranks.length, 0), 'ranks; world assets:', rows.filter((r) => r.world).map((r) => r.id).join(','), '; no cut bones:', rows.filter((r) => !r.finisher.cut).map((r) => r.id).join(',') || 'none');
