/* global URL, process */
// Writes public/game/legends.js, the /game page's copy of src/legends.ts (the page is static and its CSP allows only 'self' scripts).
// Run it after any change to src/legends.ts; tests/game-page.test.ts fails while the two differ.
import { writeFileSync } from 'node:fs';
import { LEGENDS, LEGEND_OPPONENTS } from '../src/legends.ts';

export const OUT = new URL('../public/game/legends.js', import.meta.url);
export const render = () => `// Generated by scripts/game-legends.mjs from src/legends.ts. Do not edit by hand.\nwindow.FD_LEGENDS = ${JSON.stringify(Object.fromEntries(LEGEND_OPPONENTS.map(id => [id, LEGENDS[id]])))};\n`;

if (import.meta.url === `file://${process.argv[1]}`) writeFileSync(OUT, render());
