// Writes origins/zones/registry.ts: one import block per zone folder (origins/zones/zone<N>/), so adding a zone is adding its folder and nothing else (Dom 2026-10-09, plug and play).
// `node scripts/gen-zones.mjs` rewrites it; the vite build runs it first; tests/zone-registry.test.ts fails if the committed file is stale.
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const ZONES_DIR = fileURLToPath(new URL('../origins/zones/', import.meta.url));
const REQUIRED = ['zone.ts', 'spawns.ts', 'kit.ts', 'look.ts'], OPTIONAL = [['mob-looks.ts', 'mobLooks']];

// The zone folders under `dir` (zone1, zone2, ... zone99), by number. A folder missing a required file is an error, never skipped.
export function zoneFolders(dir = ZONES_DIR) {
  return readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory() && /^zone\d+$/.test(e.name)).map((e) => e.name).sort((a, b) => Number(a.slice(4)) - Number(b.slice(4)))
    .map((name) => {
      const missing = REQUIRED.filter((f) => !existsSync(`${dir}${name}/${f}`));
      if (missing.length) throw new Error(`${name} is missing ${missing.join(', ')}`);
      return { name, id: String(Number(name.slice(4))), optional: OPTIONAL.filter(([f]) => existsSync(`${dir}${name}/${f}`)) };
    });
}
export function registrySource(dir = ZONES_DIR) {
  const zs = zoneFolders(dir), lines = ['// GENERATED by scripts/gen-zones.mjs from the origins/zones/zone<N>/ folders: do not edit (npm run zones).'];
  for (const z of zs) {
    lines.push(`import zone${z.id} from './${z.name}/zone.ts';`, `import spawns${z.id} from './${z.name}/spawns.ts';`, `import kit${z.id} from './${z.name}/kit.ts';`, `import looks${z.id} from './${z.name}/look.ts';`);
    for (const [f, key] of z.optional) lines.push(`import ${key}${z.id} from './${z.name}/${f}';`);
  }
  lines.push('', 'export const REGISTRY = {');
  for (const z of zs) lines.push(`  '${z.id}': { ...zone${z.id}, spawns: spawns${z.id}, kit: kit${z.id}, looks: looks${z.id}${z.optional.map(([, key]) => `, ${key}: ${key}${z.id}`).join('')} },`);
  lines.push('};', '');
  return lines.join('\n');
}
if (process.argv[1] === fileURLToPath(import.meta.url)) writeFileSync(`${ZONES_DIR}registry.ts`, registrySource());
