// Zone 1's creatures as data (zone-runtime step 1): the Ash Frontier's mob rows (mobs.md 7.3), moved verbatim from origins/mobs/frontier-rows.ts with the sources spelled out and the level band as numbers
// (Zone N's common creatures are level N near the town and N+1 at the edge, the named rares N+2, Dom 2026-10-08: loadZone checks every common row is [level, level+1]). Every source is public-domain folklore,
// chronicle or literature (legends-rule), no living-religion scripture. Named creatures (Hrungnir, the Mere-Mother, the bounty foes) stay on their encounters and have no row. origins/preview/mobs.golden.json pins the list.
// `openers`: a zone that is not safe opens with a fight inside 10 s of its entry (zone-rules.ts); where the data has no creature near the entry, this names the kind that stands there as a lone opener. Zone id -> row id.
// Donor: field names only (ModernUO spawn fields, Cataclysm place_monsters), nothing copied.
import type { MobRow } from '../../mobs/row.ts';

const spawns: { openers: Record<string, string>; rows: MobRow[] } = {
  openers: {"ferry-landing": "character:mere-brood", "cinder-fields": "character:cinder-scavenger"},
  rows: [
    {"id": "character:cinder-scavenger", "source": {"kind": "chronicle", "work": "Historia Ecclesiastica (the demon St Taurinus drove from the temple of Diana at Evreux, whom the people call Gobelinus)", "author": "Orderic Vitalis", "year": 1141, "authorDied": 1142, "locator": "Bk. V (Le Prevost, vol. 3, p. 331; ch. 7 in Chibnall): \"Hunc vulgus Gobelinum appellat\""}, "role": "beast", "loot": "loottable:cinder-scavenger", "level": [1, 2], "behaviour": {"roam": 8, "spread": 16, "pull": 0, "campSize": [4, 4]}},
    {"id": "character:mere-brood", "source": {"kind": "literature", "work": "Beowulf (Hrothgar's mere and its nicors)", "author": "anonymous, Old English", "year": 1000, "locator": "ll. 1357-1379 (the mere), 1408-1428 (the nicors' homes; nicors on the ledges, l. 1427)"}, "role": "beast", "loot": "loottable:mere-brood", "level": [1, 2], "behaviour": {"roam": 6, "spread": 9, "pull": 0, "campSize": [4, 4]}},
    {"id": "character:ruin-ghoul", "source": {"kind": "folklore", "work": "Les Mille et une nuits (the graveyard ghouls); read in Andrew Lang's 1898 Arabian Nights Entertainments, from Galland", "author": "Antoine Galland (translator)", "year": 1704, "authorDied": 1715, "locator": "Histoire de Sidi-Nouman (\"The Story of Sidi-Nouman\"): his wife Amina and the female ghoul of the cemetery"}, "role": "brute", "loot": "loottable:ruin-ghoul", "level": [1, 2], "behaviour": {"roam": 6, "spread": 7, "pull": 9, "campSize": [3, 3]}},
    {"id": "character:cinder-bear", "source": {"kind": "folklore", "work": "Kinder- und Hausmärchen, 7th ed. (Schneeweißchen und Rosenrot: the bear at the cottage door in the snow)", "author": "Jacob and Wilhelm Grimm", "year": 1857, "authorDied": 1863, "locator": "KHM 161, Schneeweißchen und Rosenrot (the bear knocks; the winter-door scene)"}, "role": "brute", "loot": "loottable:cinder-bear", "level": [1, 2], "weight": 0.3, "respawnSeconds": 75, "behaviour": {"aggro": 8, "roam": 6, "spread": 6, "pull": 0, "campSize": [1, 1]}},
    {"id": "character:ash-boar", "source": {"kind": "literature", "work": "Metamorphoses (the boar Diana loosed on Calydon, and the hunt that took it)", "author": "Ovid", "year": 8, "authorDied": 17, "locator": "Bk. VIII, ll. 260-424 (the boar ravages the fields; the hunt)"}, "role": "beast", "loot": "loottable:ash-boar", "level": [1, 2], "weight": 3, "respawnSeconds": 75, "behaviour": {"aggro": 6, "roam": 5, "spread": 8, "pull": 0, "campSize": [1, 1]}},
    {"id": "character:ash-wolf", "source": {"kind": "folklore", "work": "Kinder- und Hausmärchen, 7th ed. (Rotkäppchen: the wolf on the forest road)", "author": "Jacob and Wilhelm Grimm", "year": 1857, "authorDied": 1863, "locator": "KHM 26, Rotkäppchen (the wolf meets her on the path)"}, "role": "beast", "loot": "loottable:ash-wolf", "level": [1, 2], "respawnSeconds": 75, "behaviour": {"aggro": 9, "roam": 7, "spread": 10, "pull": 0, "campSize": [2, 3]}},
  ],
};
export default spawns;
